name: Pull Request Checks

on:
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Install ESLint
      run: npm install eslint eslint-plugin-node --save-dev

    - name: Create ESLint config
      run: |
        echo '{
          "env": {
            "node": true,
            "jest": true
          },
          "extends": ["eslint:recommended", "plugin:node/recommended"],
          "rules": {
            "node/exports-style": ["error", "module.exports"],
            "node/no-unsupported-features/es-syntax": "off"
          }
        }' > .eslintrc.json

    - name: Run ESLint
      run: npx eslint .

  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run tests
      run: npm test

    - name: Generate test coverage report
      run: npm run test:coverage

    - name: Report test coverage as PR comment
      uses: romeovs/lcov-reporter-action@v0.3.1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        lcov-file: ./coverage/lcov.info
